const KEY='wakg-review-decisions-v1';
const state={queue:null,paper:0,page:1,zoom:1,tab:'mix',activeEvidence:null,decisions:{},note:''};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const paper=()=>state.queue.papers[state.paper];
const page=()=>paper().pages.find(item=>item.number===state.page);
const decision=()=>state.decisions[paper().paperKey];
const svg={left:'←',right:'→',prev:'‹',next:'›',zoomOut:'−',zoomIn:'+',check:'✓',close:'×',download:'⇩',focus:'⌖'};

function loadDecisions(){try{state.decisions=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{state.decisions={}}}
function saveDecisions(){localStorage.setItem(KEY,JSON.stringify(state.decisions))}
function statusLabel(value){return value==='accepted'?'整篇论文：已接受':value==='rejected'?'整篇论文：已拒绝':'整篇论文：待审核'}
const SOURCE_EXPLANATION_TEMPLATES=Object.freeze({'DIRECT_SOURCE_VALUE':'原文直接报告','SOURCE_DERIVED_VALUE':'根据原文换算','SOURCE_COMPOSITE_VALUE':'根据原文多个字段组合','SOURCE_DASH_NO_VALUE':'原表为“/”（无数值）','SOURCE_NOT_REPORTED':'原文未报告','SOURCE_NOT_APPLICABLE':'该字段不适用','SOURCE_LOCATED_NOT_TRANSCRIBED':'已定位，尚未转录','SOURCE_CANDIDATE_CONVERSION':'原文换算候选（非正式值）','SYSTEM_PROCESSING_NOTE':'系统处理说明','SOURCE_EVIDENCE_BLOCKED':'来源未通过自动核验'});
const SOURCE_EXPLANATION_TEMPLATE_VERSION=1;
function sourceExplanation(field){return SOURCE_EXPLANATION_TEMPLATES[field.sourceExplanationCode]}
function validSourceExplanation(field){const label=sourceExplanation(field);return Boolean(label)&&field.sourceExplanation===label}
function validSourceExplanationContract(contract){if(contract?.version!==SOURCE_EXPLANATION_TEMPLATE_VERSION)return false;const templates=contract.templates;if(!templates||Object.keys(templates).length!==Object.keys(SOURCE_EXPLANATION_TEMPLATES).length)return false;return Object.entries(SOURCE_EXPLANATION_TEMPLATES).every(([code,label])=>templates[code]===label)}
const FIELD_LABELS={'GGBS':'粒化高炉矿渣粉（GGBS）','FA':'粉煤灰（FA）','Na2O.SiO2':'Na₂O·SiO₂（原文组分名）','Na2O.2SiO2':'Na₂O·2SiO₂（原文组分名）','Na2CO3':'碳酸钠（Na₂CO₃）','Na2SO4':'硫酸钠（Na₂SO₄）','Borax':'硼砂（Borax）','Water':'水（Water）','QS#1':'石英砂 1（QS#1）','QS#2':'石英砂 2（QS#2）'};
function reviewerFieldLabel(field){return FIELD_LABELS[field.label]||field.label}
function allEvidence(){return paper().pages.flatMap(item=>item.evidence)}
function reviewerRecordTitle(record,index){const specimen=record.fields.find(field=>field.label==='试样')?.value;if(record.kind?.startsWith('MIX'))return `配比 ${index+1}${specimen?` · 试样 ${specimen}`:''}`;return `原材料 ${index+1}`}

function comparisonColumns(records){const seen=new Set(),columns=[];records.forEach(record=>record.fields.forEach(field=>{if(!seen.has(field.label)){seen.add(field.label);columns.push(field.label)}}));return columns}
function comparisonCell(record,label){const field=record.fields.find(item=>item.label===label);if(!field)return '<td class="matrix-cell matrix-cell--missing"><span>—</span><small>此记录无此字段</small></td>';
  const hasValue=field.value!==null&&field.value!==undefined&&field.value!=='';const linked=hasValue&&Boolean(field.evidenceKey)&&!field.evidenceBlocked,active=linked&&field.evidenceKey===state.activeEvidence,displayed=hasValue?field.value:'无数值';
  return `<td class="matrix-cell ${active?'matrix-cell--active':''} ${hasValue?'':'matrix-cell--absent'}"><button class="matrix-value ${linked?'linked':''}" ${linked?'':`disabled`} data-evidence="${esc(linked?field.evidenceKey:'')}" title="${esc(sourceExplanation(field))}${linked?'；点击定位原文':''}"><strong>${esc(displayed)}</strong>${hasValue&&field.unit?`<small>${esc(field.unit)}</small>`:''}<span class="source-line"><em class="source-kind">来源类型：${esc(sourceExplanation(field))}</em>${linked?`<b class="source-action">${svg.focus} 定位原文</b>`:''}</span></button></td>`}
function recordsTableHtml(records){const columns=comparisonColumns(records);return `<div class="matrix-wrap"><div class="matrix-help"><strong>表格对照（左右滚动可看全部 ${columns.length} 个字段）：</strong>每条记录一行、每个字段一列；点击红色“定位原文”核对左侧证据。<span>“试样”和“养护条件”是 WAKG V1.1.4 指定字段；其他列只沿用论文原表实际出现的字段名，不新增科学字段。</span></div><table class="comparison-table"><thead><tr><th class="matrix-record-head" scope="col">记录</th>${columns.map(label=>`<th class="${label==='养护条件'?'matrix-long':''}" scope="col">${esc(reviewerFieldLabel({label}))}</th>`).join('')}</tr></thead><tbody>${records.map((record,index)=>`<tr><th class="matrix-record" scope="row"><strong>${esc(reviewerRecordTitle(record,index))}</strong><small>${esc(record.kind?.startsWith('MIX')?'MIX：配比及性能记录':'MAT：原材料记录')}</small></th>${columns.map(label=>comparisonCell(record,label)).join('')}</tr>`).join('')}</tbody></table></div>`}
function recordsHtml(){const p=paper(),records=p.records[state.tab==='mat'?'mats':'mixes'];return records.length?recordsTableHtml(records):`<div class="empty">${p.extractionStatus==='NOT_EXTRACTED'?'此论文尚未运行提取流程':'这一类没有提取记录'}</div>`}
function evidenceHtml(item){const[x0,y0,x1,y1]=item.bbox,p=page();return `<button aria-label="${esc(item.recordKey)} 的精确原文来源" class="evidence ${state.activeEvidence===item.evidenceKey?'active':''}" data-box="${esc(item.evidenceKey)}" style="left:${x0/p.width*100}%;top:${y0/p.height*100}%;width:${(x1-x0)/p.width*100}%;height:${(y1-y0)/p.height*100}%" title="${esc(item.locator)}: ${esc(item.snippet)}"></button>`}

function captureView(){const records=$('.record-scroll'),stage=$('.stage');return {recordTop:records?.scrollTop||0,recordLeft:records?.scrollLeft||0,stageTop:stage?.scrollTop||0,stageLeft:stage?.scrollLeft||0,stageAnchorX:stage?.scrollWidth?(stage.scrollLeft+stage.clientWidth/2)/stage.scrollWidth:.5,stageAnchorY:stage?.scrollHeight?(stage.scrollTop+stage.clientHeight/2)/stage.scrollHeight:.5}}
function restoreView(view,{centerEvidence=false,anchorStage=false}={}){requestAnimationFrame(()=>{const records=$('.record-scroll'),stage=$('.stage');if(records&&view){records.scrollTop=view.recordTop;records.scrollLeft=view.recordLeft}if(!stage)return;if(centerEvidence&&state.activeEvidence){const box=stage.querySelector(`[data-box="${CSS.escape(state.activeEvidence)}"]`);if(box){const sr=stage.getBoundingClientRect(),br=box.getBoundingClientRect();stage.scrollLeft+=br.left+br.width/2-(sr.left+sr.width/2);stage.scrollTop+=br.top+br.height/2-(sr.top+sr.height/2);return}}if(anchorStage&&view){stage.scrollLeft=view.stageAnchorX*stage.scrollWidth-stage.clientWidth/2;stage.scrollTop=view.stageAnchorY*stage.scrollHeight-stage.clientHeight/2}else if(view){stage.scrollLeft=view.stageLeft;stage.scrollTop=view.stageTop}})}
function render(options={}){const p=paper(),pg=page(),d=decision(),pending=p.extractionStatus==='NOT_EXTRACTED',reviewPending=p.extractionStatus==='EXTRACTED',visibleEvidence=state.activeEvidence?pg.evidence.filter(item=>item.evidenceKey===state.activeEvidence):[],view=options.view||null;document.getElementById('app').className='shell';document.getElementById('app').innerHTML=`
<header class="topbar"><div class="brand"><div class="brand-mark">W</div><div><p class="eyebrow">WAKG · 论文材料与配比数据</p><h1>论文数据人工审核台</h1></div></div><div class="paper-nav"><button class="btn" data-action="paper-prev" ${state.paper===0?'disabled':''}>上一篇</button><div class="paper-index"><strong>论文 ${state.paper+1}</strong><span> / ${state.queue.papers.length}</span><small>${Object.keys(state.decisions).length} 篇已审核</small></div><button class="btn" data-action="paper-next" ${state.paper===state.queue.papers.length-1?'disabled':''}>下一篇</button></div><div class="top-actions"><span class="status ${d?.status||''}">${d?.status==='accepted'?svg.check:d?.status==='rejected'?svg.close:''} ${statusLabel(d?.status)}</span><button class="btn" data-action="export">${svg.download} 导出审核记录</button></div></header>
<section class="paper-strip"><div class="paper-title"><h2>${esc(p.title)}</h2><p>${esc(p.citation)}</p></div><div class="paper-meta">${p.doi&&p.doi!=='unavailable'?`<a href="https://doi.org/${esc(p.doi)}" target="_blank" rel="noreferrer">论文 DOI：${esc(p.doi)} ↗</a>`:'<span>论文 DOI 未识别</span>'}${pending?'<span class="tag">系统状态：待提取</span>':''}${reviewPending?'<span class="tag">系统状态：提取完成</span>':''}<span class="tag" title="Agent 已核对字段结构、数值与原文定位；最终决定仍由人工完成">Agent 已核对自动提取与原文证据</span></div></section>
<div class="workspace"><section class="document"><div class="toolbar"><div class="page-nav"><button class="btn" data-action="page-prev" ${state.page===1?'disabled':''}>上一页</button><span>第 <b>${state.page}</b> / ${p.pageCount} 页</span><button class="btn" data-action="page-next" ${state.page===p.pageCount?'disabled':''}>下一页</button></div><div class="zoom"><span class="legend"><i></i>红框：当前数值在论文中的来源</span><button class="btn icon-btn" data-action="zoom-out">${svg.zoomOut}</button><span>${Math.round(state.zoom*100)}%</span><button class="btn icon-btn" data-action="zoom-in">${svg.zoomIn}</button></div></div><div class="stage" aria-label="可滚动和拖动的论文页面"><div class="pdf-page" style="width:${pg.width*state.zoom}px;aspect-ratio:${pg.width}/${pg.height}"><img src="${esc(pg.imageUrl)}" alt="论文第 ${pg.number} 页" draggable="false">${visibleEvidence.map(evidenceHtml).join('')}</div></div><div class="doc-foot"><span>${state.activeEvidence?`当前显示该字段的 ${visibleEvidence.length} 个来源红框`:`本页尚无选中的数值。点击右侧“定位原文”会自动跳到来源页`} · 放大后可拖动论文 · 本页共 ${pg.evidence.length} 个可定位来源</span><a href="${esc(p.pdfUrl)}" target="_blank" rel="noreferrer">在新窗口打开完整 PDF ↗</a></div></section>
<aside class="data"><div class="data-head"><div><p class="eyebrow">结构化提取结果</p><h2>${pending?'尚未提取数据':'等待最终人工审核'}</h2></div><span class="integrity neutral" title="Agent 预审不替代最终人工决定">Agent 预审：结构、数值、证据定位均通过</span></div><div class="review-guide"><strong>页面字段：</strong>MAT＝原材料记录；MIX＝配比、养护与性能记录；“试样”保留论文原编号。每个数值后的单位表示其数据类型，红字“来源类型”说明数值如何取得。<br><strong>审核操作：</strong>切换 MAT/MIX 并左右滚动查看字段；点击“定位原文”后左侧自动翻页并显示小红框。复合字段会一次显示全部来源红框。<br><strong>数值规则：</strong>原表的“/”显示“无数值”，只有原文明确的 0 才显示为 0。</div><div class="tabs">${[['mat','原材料 MAT',p.records.mats.length],['mix','配比 MIX',p.records.mixes.length]].map(([key,label,count])=>`<button class="tab ${state.tab===key?'active':''}" data-tab="${key}">${label}<b>${count}</b></button>`).join('')}</div><div class="record-scroll">${recordsHtml()}</div><div class="review"><div class="review-head"><div><p class="eyebrow">当前整篇论文的人工决定</p><h3>审核结论</h3></div>${d?'<button class="btn" data-action="clear">↻ 撤销本论文的决定</button>':''}</div><textarea class="note" placeholder="可选填写审核备注；拒绝时请说明问题字段和原因。">${esc(state.note)}</textarea><div class="decision-row"><button class="btn reject" data-action="reject">${svg.close} 拒绝整篇论文</button><button class="btn accept" data-action="accept" title="接受当前显示的整篇论文结果">${svg.check} 接受本论文</button></div><p class="local-note">决定只保存在本机审核记录中；导出后交给流水线验收，不会自动写入 WAKG。</p></div></aside></div>`;if(view)restoreView(view,{centerEvidence:Boolean(options.centerEvidence),anchorStage:Boolean(options.anchorStage)});
}

function changePaper(delta){const next=Math.max(0,Math.min(state.queue.papers.length-1,state.paper+delta));if(next===state.paper)return;state.paper=next;state.page=1;state.zoom=1;state.tab='mix';state.activeEvidence=null;state.note=state.decisions[paper().paperKey]?.note||'';render()}
function decide(status){state.note=$('.note')?.value.trim()||'';if(status==='rejected'&&!state.note){alert('拒绝时请填写问题字段和原因。');return}state.decisions[paper().paperKey]={status,note:state.note,decidedAt:new Date().toISOString()};saveDecisions();if(state.paper<state.queue.papers.length-1)changePaper(1);else render()}
function jumpEvidence(key){const item=allEvidence().find(value=>value.evidenceKey===key);if(!item)return;const view=captureView();state.page=item.page;state.activeEvidence=key;render({view,centerEvidence:true})}
function changeZoom(delta){const view=captureView();state.zoom=Math.max(.7,Math.min(2.5,state.zoom+delta));render({view,anchorStage:true})}
function exportDecisions(){const payload=JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),queueGeneratedAt:state.queue.generatedAt,decisions:state.decisions},null,2),url=URL.createObjectURL(new Blob([payload],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='wakg-review-decisions.json';a.click();URL.revokeObjectURL(url)}

document.addEventListener('click',event=>{const target=event.target.closest('button,[data-tab]');if(!target)return;if(target.dataset.tab){state.tab=target.dataset.tab;render();return}if(target.dataset.evidence){jumpEvidence(target.dataset.evidence);return}if(target.dataset.box){state.activeEvidence=target.dataset.box;render();return}const action=target.dataset.action;if(!action)return;({
  'paper-prev':()=>changePaper(-1),'paper-next':()=>changePaper(1),'page-prev':()=>{state.page=Math.max(1,state.page-1);state.activeEvidence=null;render()},'page-next':()=>{state.page=Math.min(paper().pageCount,state.page+1);state.activeEvidence=null;render()},'zoom-out':()=>changeZoom(-.1),'zoom-in':()=>changeZoom(.1),accept:()=>decide('accepted'),reject:()=>decide('rejected'),clear:()=>{delete state.decisions[paper().paperKey];state.note='';saveDecisions();render()},export:exportDecisions
}[action]||(()=>{}))()});
document.addEventListener('input',event=>{if(event.target.matches('.note'))state.note=event.target.value});
let dragState=null;
document.addEventListener('pointerdown',event=>{const stage=event.target.closest?.('.stage');if(!stage||event.target.closest('button,a'))return;dragState={stage,id:event.pointerId,x:event.clientX,y:event.clientY,left:stage.scrollLeft,top:stage.scrollTop};stage.setPointerCapture?.(event.pointerId);stage.classList.add('dragging');event.preventDefault()});
document.addEventListener('pointermove',event=>{if(!dragState||event.pointerId!==dragState.id)return;dragState.stage.scrollLeft=dragState.left-(event.clientX-dragState.x);dragState.stage.scrollTop=dragState.top-(event.clientY-dragState.y)});
function endDrag(event){if(!dragState||event.pointerId!==dragState.id)return;dragState.stage.classList.remove('dragging');dragState=null}
document.addEventListener('pointerup',endDrag);document.addEventListener('pointercancel',endDrag);

loadDecisions();fetch('review-assets/queue.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error(`审核队列加载失败 (${response.status})`);return response.json()}).then(queue=>{if(!queue.papers?.length)throw new Error('审核队列为空');const fields=queue.papers.flatMap(p=>['mats','mixes','quarantined'].flatMap(name=>p.records[name]||[])).flatMap(record=>record.fields||[]);const repairState=fields.some(field=>field.evidenceBlocked||field.status==='evidence_blocked'||field.status==='not_extracted'||field.sourceExplanationCode==='SOURCE_LOCATED_NOT_TRANSCRIBED'||String(field.statusLabel||'').includes('待修复')||String(field.reason||'').includes('待修复'));const sourceContractReady=validSourceExplanationContract(queue.sourceExplanationContract)&&fields.every(validSourceExplanation);const agentReady=queue.preHumanAgentReview?.verdict==='PASS'&&queue.preHumanAgentReview?.subjectSha256&&queue.preHumanAgentReview?.receiptSha256;if(queue.reviewReadiness!=='FINAL_REVIEW_READY'||repairState||!sourceContractReady||!agentReady)throw new Error('审核数据尚未通过最终发布门禁');state.queue=queue;state.note=state.decisions[paper().paperKey]?.note||'';render()}).catch(()=>{document.getElementById('app').innerHTML=`<div class="load-card"><h1>审核数据暂不可用</h1><p>请稍后刷新。</p></div>`});
